server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  prefix: /lwen  #服务前缀
  ignored-services: "*"
  routes:
    mydept.serviceId: cloud-dept
    mydept.path: /mydept/**   #服务路径  后面接的就是我们的controller 的地址


